name = "hello_world"
description = "Hello, World example"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["hello_world"]

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"

[build-profiles]
slides_as_code = "development"

[[depends-on]]
slides_as_code = "~0.1.0-dev"

[[pins]]
slides_as_code = { path='../..' }
